# Copyright (c) 2021 - 2026, Ilan Schnell; All Rights Reserved

from collections import Counter
from collections.abc import Iterable, Iterator, Sequence
from typing import Any, AnyStr, BinaryIO, Optional, Union

from pauliebits import pauliebits, BytesLike, CodeDict


FreqMap = Union[Counter[int], dict[Any, Union[int, float]]]


def zeros(length: int, endian: Optional[str] = ...) -> pauliebits: ...
def ones(length: int, endian: Optional[str] = ...) -> pauliebits: ...

def urandom(length: int, endian: Optional[str] = ...) -> pauliebits: ...
def random_p(n: int,
             p = ...,
             endian: Optional[str] = ...) -> pauliebits: ...
def random_k(n: int,
             k: int,
             endian: Optional[str] = ...) -> pauliebits: ...
def gen_primes(n: int,
               endian: Optional[str] = ...,
               odd: Optional[bool] = ...) -> pauliebits: ...

def pprint(a: Any, stream: BinaryIO = ...,
           group: int = ...,
           indent: int = ...,
           width: int = ...) -> None: ...

def strip(a: pauliebits, mode: str = ...) -> pauliebits: ...

def count_n(a: pauliebits,
            n: int,
            value: int = ...) -> int: ...

def parity(a: pauliebits) -> int: ...
def sum_indices(a: pauliebits, mode: int = ...) -> int: ...
def xor_indices(a: pauliebits) -> int: ...
def count_and(a: pauliebits, b: pauliebits) -> int: ...
def count_or(a: pauliebits, b: pauliebits) -> int: ...
def count_xor(a: pauliebits, b: pauliebits) -> int: ...
def any_and(a: pauliebits, b: pauliebits) -> bool: ...
def subset(a: pauliebits, b: pauliebits) -> bool: ...
def correspond_all(a: pauliebits, b: pauliebits) -> tuple: ...
def byteswap(a: BytesLike, n: int) -> None: ...

def intervals(a: pauliebits) -> Iterator: ...

def ba2hex(a: pauliebits,
           group: int = ...,
           sep: str = ...) -> str: ...
def hex2ba(s: AnyStr,
           endian: Optional[str] = ...) -> pauliebits: ...
def ba2base(n: int,
            a: pauliebits,
            group: int = ...,
            sep: str = ...) -> str: ...
def base2ba(n: int,
            s: AnyStr,
            endian: Optional[str] = ...) -> pauliebits: ...

def ba2int(a: pauliebits, signed: int = ...) -> int: ...
def int2ba(i: int,
           length: int = ...,
           endian: str = ...,
           signed: int = ...) -> pauliebits: ...

def serialize(a: pauliebits) -> bytes: ...
def deserialize(b: BytesLike) -> pauliebits: ...
def sc_encode(a: pauliebits) -> bytes: ...
def sc_decode(stream: Iterable[int]) -> pauliebits: ...
def vl_encode(a: pauliebits) -> bytes: ...
def vl_decode(stream: Iterable[int],
              endian: Optional[str] = ...) -> pauliebits: ...

def _huffman_tree(freq_map: FreqMap) -> Any: ...
def huffman_code(freq_map: FreqMap,
                 endian: Optional[str] = ...) -> CodeDict: ...
def canonical_huffman(Freq_Map) -> tuple[CodeDict, list, list]: ...
def canonical_decode(a: pauliebits,
                     count: Sequence[int],
                     symbol: Iterable[Any]) -> Iterator: ...
